// Adding all the HTML Elements in a NodeList
var htmlElementsOfWholeDocument = document.querySelectorAll("*");

function addCssProperty(propertyNameAsAttribute, propertyNameAsCss) {
	htmlElementsOfWholeDocument.forEach( (el) => {
		if ( value = el.getAttribute(propertyNameAsAttribute) ) {
			el.style[propertyNameAsCss] = value;
		}
	} );
}

// "A"
addCssProperty("p-align-content", "align-content");
addCssProperty("p-align-items", "align-items");
addCssProperty("p-align-self", "align-self");
addCssProperty("p-all", "all");
addCssProperty("p-animation-name", "animation-name");
addCssProperty("p-animation-duration", "animation-duration");
addCssProperty("p-animation-timing-function", "animation-timing-function");
addCssProperty("p-animation-delay", "animation-delay");
addCssProperty("p-animation-iteration-count", "animation-iteration-count");
addCssProperty("p-animation-direction", "animation-direction");
addCssProperty("p-animation-fill-mode", "animation-fill-mode");
addCssProperty("p-animation-play-state", "animation-play-state");
// "B"
addCssProperty("p-backface-visibility", "backface-visibility");
addCssProperty("p-background-color", "background-color");
addCssProperty("p-background-image", "background-image");
addCssProperty("p-background-position", "background-position");
addCssProperty("p-background-size", "background-size");
addCssProperty("p-background-repeat", "background-repeat");
addCssProperty("p-background-origin", "background-origin");
addCssProperty("p-background-clip", "background-clip");
addCssProperty("p-background-attachment", "background-attachment");
addCssProperty("p-border-width", "border-width");
addCssProperty("p-border-style", "border-style");
addCssProperty("p-border-color", "border-color");
addCssProperty("p-border-radius", "border-radius");
addCssProperty("p-border-top-width", "border-top-width");
addCssProperty("p-border-top-style", "border-top-style");
addCssProperty("p-border-top-color", "border-top-color");
addCssProperty("p-border-top-radius", "border-top-radius");
addCssProperty("p-border-bottom-width", "border-bottom-width");
addCssProperty("p-border-bottom-style", "border-bottom-style");
addCssProperty("p-border-bottom-color", "border-bottom-color");
addCssProperty("p-border-bottom-radius", "border-bottom-radius");
addCssProperty("p-border-left-width", "border-left-width");
addCssProperty("p-border-left-style", "border-left-style");
addCssProperty("p-border-left-color", "border-left-color");
addCssProperty("p-border-left-radius", "border-left-radius");
addCssProperty("p-border-right-width", "border-right-width");
addCssProperty("p-border-right-style", "border-right-style");
addCssProperty("p-border-right-color", "border-right-color");
addCssProperty("p-border-right-radius", "border-right-radius");
addCssProperty("p-table-border-collapse", "border-collapse");
addCssProperty("p-border-image-source", "border-image-source");
addCssProperty("p-border-image-slice", "border-image-slice");
addCssProperty("p-border-image-width", "border-image-width");
addCssProperty("p-border-image-outset", "border-image-outset");
addCssProperty("p-border-image-repeat", "border-image-repeat");
addCssProperty("p-bottom", "bottom");
addCssProperty("p-box-decoration-break", "box-decoration-break");
addCssProperty("p-box-shadow", "box-shadow");
addCssProperty("p-box-sizing", "box-sizing");
addCssProperty("p-break-after", "break-after");
addCssProperty("p-break-before", "break-before");
addCssProperty("p-break-inside", "break-inside");
// "C"
addCssProperty("p-table-caption-side", "caption-side");
addCssProperty("p-input-caret-color", "caret-color");
addCssProperty("p-no-float", "clear");
addCssProperty("p-clip-path", "clip-path");
addCssProperty("p-text-color", "color");
addCssProperty("p-column-count", "column-count");
addCssProperty("p-column-fill", "column-fill");
addCssProperty("p-column-gap", "column-gap");
addCssProperty("p-column-border-width", "column-rule-width");
addCssProperty("p-column-border-style", "column-rule-style");
addCssProperty("p-column-border-color", "column-rule-color");
addCssProperty("p-column-cover", "column-span");
addCssProperty("p-column-width", "column-width");
addCssProperty("p-column-width", "column-width");
addCssProperty("p-mouse-cursor", "cursor");
// "D"
addCssProperty("p-text-direction", "direction");
addCssProperty("p-display-behaviour", "display");
// "E"
addCssProperty("p-table-empty-cells", "empty-cells");
// "F"
addCssProperty("p-filter", "filter");
addCssProperty("p-flex", "flex");
addCssProperty("p-flex-item-width", "flex-basis");
addCssProperty("p-flex-direction", "flex-direction");
addCssProperty("p-flex-grow-ratio", "flex-grow");
addCssProperty("p-flex-shrink-ratio", "flex-shrink");
addCssProperty("p-flex-wrap", "flex-wrap");
addCssProperty("p-float", "float");
addCssProperty("p-font-style", "font-style");
addCssProperty("p-font-variant", "font-variant");
addCssProperty("p-font-weight", "font-weight");
addCssProperty("p-font-size", "font-size");
addCssProperty("p-font-family", "font-family");
addCssProperty("p-font-feature-settings", "font-feature-settings");
addCssProperty("p-font-kerning", "font-kerning");
addCssProperty("p-font-stretch", "font-stretch");
addCssProperty("p-font-variant-caps", "font-variant-caps");
// "G"
addCssProperty("p-grid-row-count", "grid-template-rows");
addCssProperty("p-grid-column-count", "grid-template-columns");
addCssProperty("p-grid-specify-areas", "grid-template-areas");
addCssProperty("p-grid-row-size", "grid-auto-rows");
addCssProperty("p-grid-column-size", "grid-auto-columns");
addCssProperty("p-grid-flow", "grid-auto-flow");
addCssProperty("p-grid-row-start", "grid-row-start");
addCssProperty("p-grid-column-start", "grid-column-start");
addCssProperty("p-grid-row-end", "grid-row-end");
addCssProperty("p-grid-column-end", "grid-column-end");
addCssProperty("p-grid-gap", "grid-gap");
addCssProperty("p-grid-column-gap", "grid-column-gap");
addCssProperty("p-grid-row-gap", "grid-row-gap");
// "H"
addCssProperty("p-height", "height");
addCssProperty("p-hyphens", "hyphens");
// "I"
addCssProperty("p-isolation", "isolation");
// "J"
addCssProperty("p-justify-content", "justify-content");
// "L"
addCssProperty("p-left", "left");
addCssProperty("p-letter-spacing", "letter-spacing");
addCssProperty("p-line-height", "line-height");
addCssProperty("p-list-style-type", "list-style-type");
addCssProperty("p-list-style-position", "list-style-position");
addCssProperty("p-list-style-image", "list-style-image");
// "M"
addCssProperty("p-margin", "margin");
addCssProperty("p-margin-top", "margin-top");
addCssProperty("p-margin-bottom", "margin-bottom");
addCssProperty("p-margin-left", "margin-left");
addCssProperty("p-margin-right", "margin-right");
addCssProperty("p-max-height", "max-height");
addCssProperty("p-max-width", "max-width");
addCssProperty("p-min-height", "min-height");
addCssProperty("p-min-width", "min-width");
addCssProperty("p-mix-blend-mode", "mix-blend-mode");
// "O"
addCssProperty("p-object-fit", "object-fit");
addCssProperty("p-object-position", "object-position");
addCssProperty("p-opacity", "opacity");
addCssProperty("p-order", "order");
addCssProperty("p-outline-width", "outline-width");
addCssProperty("p-outline-style", "outline-style");
addCssProperty("p-outline-color", "outline-color");
addCssProperty("p-outline-offset", "outline-offset");
addCssProperty("p-overflow", "overflow");
addCssProperty("p-overflow-x", "overflow-x");
addCssProperty("p-overflow-y", "overflow-y");
// "P"
addCssProperty("p-padding", "padding");
addCssProperty("p-padding-top", "padding-top");
addCssProperty("p-padding-bottom", "padding-bottom");
addCssProperty("p-padding-left", "padding-left");
addCssProperty("p-padding-right", "padding-right");
addCssProperty("p-page-break-after", "page-break-after");
addCssProperty("p-page-break-before", "page-break-before");
addCssProperty("p-page-break-inside", "page-break-inside");
addCssProperty("p-perspective", "perspective");
addCssProperty("p-perspective-origin", "perspective-origin");
addCssProperty("p-pointer-events", "pointer-events");
addCssProperty("p-position", "position");
// "Q"
addCssProperty("p-define-quotes", "quotes");
// "R"
addCssProperty("p-resizable", "resize");
addCssProperty("p-right", "right");
// "S"
addCssProperty("p-scroll-behavior", "scroll-behavior");
// "T"
addCssProperty("p-tag-size", "tag-size");
addCssProperty("p-table-layout", "table-layout");
addCssProperty("p-text-align", "text-align");
addCssProperty("p-text-align-last-line", "text-align-last");
addCssProperty("p-text-decoration", "text-decoration");
addCssProperty("p-text-decoration-color", "text-decoration-color");
addCssProperty("p-text-decoration-style", "text-decoration-style");
addCssProperty("p-text-indent", "text-indent");
addCssProperty("p-justify-text", "text-justify");
addCssProperty("p-text-overflow", "text-overflow");
addCssProperty("p-text-shadow", "text-shadow");
addCssProperty("p-text-transform", "text-transform");
addCssProperty("p-top", "top");
addCssProperty("p-transform", "transform");
addCssProperty("p-transform-origin", "transform-origin");
addCssProperty("p-transform-style", "transform-style");
addCssProperty("p-transition-property", "transition-property");
addCssProperty("p-transition-duration", "transition-duration");
addCssProperty("p-transition-timing-function", "transition-timing-function");
addCssProperty("p-transition-delay", "transition-delay");
// "U"
addCssProperty("p-unicode-bidi", "unicode-bidi");
addCssProperty("p-user-select", "user-select");
// "V"
addCssProperty("p-vertical-align", "vertical-align");
addCssProperty("p-visibility", "visibility");
// "W"
addCssProperty("p-white-space", "white-space");
addCssProperty("p-width", "width");
addCssProperty("p-word-break", "word-break");
addCssProperty("p-word-spacing", "word-spacing");
addCssProperty("p-word-wrap", "word-wrap");
addCssProperty("p-writing-mode", "writing-mode");
// "Z"
addCssProperty("p-z-index", "z-index");